In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("arrestdatany.csv")
df

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,238013474,12/18/2021,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,Q,105,97,18-24,M,BLACK,1057636,203954,40.726187,-73.735234,POINT (-73.73523390399998 40.72618713000002)
1,236943583,11/25/2021,263.0,"ARSON 2,3,4",114.0,ARSON,PL 1501500,F,K,69,71,25-44,M,BLACK,1014340,171320,40.636868,-73.891586,POINT (-73.89158591899997 40.63686750900007)
2,234938876,10/14/2021,594.0,OBSCENITY 1,116.0,SEX CRIMES,PL 2631100,F,K,61,0,25-44,M,WHITE,995244,155739,40.594145,-73.960415,POINT (-73.96041495199995 40.59414516900005)
3,234788259,10/11/2021,263.0,"ARSON 2,3,4",114.0,ARSON,PL 1501001,F,B,42,71,18-24,M,BLACK,1009058,239616,40.824340,-73.910365,POINT (-73.91036538099996 40.82433953100008)
4,234188790,09/28/2021,578.0,NaN,NaN,NaN,PL 2223001,M,B,44,0,25-44,M,BLACK,1005169,246667,40.843703,-73.924395,POINT (-73.92439508899997 40.84370255600004)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,222884924,01/10/2021,397.0,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 1601001,F,B,46,0,45-64,M,BLACK,1011432,247605,40.846260,-73.901755,POINT (-73.90175529499999 40.846260031000035)
155503,223918625,02/03/2021,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 2650303,F,K,67,0,18-24,M,BLACK,1004940,180941,40.663302,-73.925425,POINT (-73.92542497899994 40.66330200400005)
155504,224323770,02/13/2021,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,S,121,0,45-64,M,BLACK,942825,166367,40.623227,-74.149227,POINT (-74.14922697299994 40.623226819000074)
155505,222599533,01/04/2021,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 2650303,F,K,73,0,25-44,M,BLACK,1007524,188555,40.684194,-73.916085,POINT (-73.91608474599997 40.684194302000044)
155506,224056881,02/06/2021,268.0,CRIMINAL MIS 2 & 3,121.0,CRIMINAL MISCHIEF & RELATED OF,PL 1451000,F,Q,102,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031414,190787,40.690226,-73.829932,POINT (-73.82993153599993 40.69022556600004)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155507 entries, 0 to 155506
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ARREST_KEY                155507 non-null  int64
 1   ARREST_DATE               155507 non-null  object
 2   PD_CD                     155478 non-null  float64
 3   PD_DESC                   155404 non-null  object
 4   KY_CD                     155404 non-null  float64
 5   OFNS_DESC                 155404 non-null  object
 6   LAW_CODE                  155507 non-null  object
 7   LAW_CAT_CD                154114 non-null  object
 8   ARREST_BORO               155507 non-null  object
 9   ARREST_PRECINCT           155507 non-null  int64
 10  JURISDICTION_CODE         155507 non-null  int64
 11  AGE_GROUP                 155507 non-null  object
 12  PERP_SEX                  155507 non-null  object
 13  PERP_RACE                 155507 non-null  object
 14  X_COORD_CD                155507 non-null  int64
 15  Y_COORD_CD                155507 non-null  int64
 16  Latitude                  155507 non-null  float64
 17  Longitude                 155507 non-null  float64
 18  New Georeferenced Column  155507 non-null  object
dtypes: float64(4), int64(5), object(10)
memory usage: 22.5+ MB

In [4]:
df.rename(columns = {"ARREST_DATE": "arrest_date", "OFNS_DESC": "offense", "ARREST_BORO": "borough", "ARREST_PRECINCT":"precinct","AGE_GROUP":"age", "PERP_SEX":"perp_sex","PERP_RACE":"perp_race","Latitude":"latitude","Longitude": "longitude" }, inplace = True)

In [5]:
df

,ARREST_KEY,arrest_date,PD_CD,PD_DESC,KY_CD,offense,LAW_CODE,LAW_CAT_CD,borough,precinct,JURISDICTION_CODE,age,perp_sex,perp_race,X_COORD_CD,Y_COORD_CD,latitude,longitude,New Georeferenced Column
0,238013474,12/18/2021,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,Q,105,97,18-24,M,BLACK,1057636,203954,40.726187,-73.735234,POINT (-73.73523390399998 40.72618713000002)
1,236943583,11/25/2021,263.0,"ARSON 2,3,4",114.0,ARSON,PL 1501500,F,K,69,71,25-44,M,BLACK,1014340,171320,40.636868,-73.891586,POINT (-73.89158591899997 40.63686750900007)
2,234938876,10/14/2021,594.0,OBSCENITY 1,116.0,SEX CRIMES,PL 2631100,F,K,61,0,25-44,M,WHITE,995244,155739,40.594145,-73.960415,POINT (-73.96041495199995 40.59414516900005)
3,234788259,10/11/2021,263.0,"ARSON 2,3,4",114.0,ARSON,PL 1501001,F,B,42,71,18-24,M,BLACK,1009058,239616,40.824340,-73.910365,POINT (-73.91036538099996 40.82433953100008)
4,234188790,09/28/2021,578.0,NaN,NaN,NaN,PL 2223001,M,B,44,0,25-44,M,BLACK,1005169,246667,40.843703,-73.924395,POINT (-73.92439508899997 40.84370255600004)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,222884924,01/10/2021,397.0,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 1601001,F,B,46,0,45-64,M,BLACK,1011432,247605,40.846260,-73.901755,POINT (-73.90175529499999 40.846260031000035)
155503,223918625,02/03/2021,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 2650303,F,K,67,0,18-24,M,BLACK,1004940,180941,40.663302,-73.925425,POINT (-73.92542497899994 40.66330200400005)
155504,224323770,02/13/2021,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,S,121,0,45-64,M,BLACK,942825,166367,40.623227,-74.149227,POINT (-74.14922697299994 40.623226819000074)
155505,222599533,01/04/2021,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 2650303,F,K,73,0,25-44,M,BLACK,1007524,188555,40.684194,-73.916085,POINT (-73.91608474599997 40.684194302000044)
155506,224056881,02/06/2021,268.0,CRIMINAL MIS 2 & 3,121.0,CRIMINAL MISCHIEF & RELATED OF,PL 1451000,F,Q,102,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031414,190787,40.690226,-73.829932,POINT (-73.82993153599993 40.69022556600004)

In [6]:
df_tidy= df[["arrest_date",
            "PD_DESC",
            "offense",
            "borough",
            "precinct",
            "age",
            "perp_sex",
            "perp_race"
            ]]

df_tidy

,arrest_date,PD_DESC,offense,borough,precinct,age,perp_sex,perp_race
0,12/18/2021,RAPE 1,RAPE,Q,105,18-24,M,BLACK
1,11/25/2021,"ARSON 2,3,4",ARSON,K,69,25-44,M,BLACK
2,10/14/2021,OBSCENITY 1,SEX CRIMES,K,61,25-44,M,WHITE
3,10/11/2021,"ARSON 2,3,4",ARSON,B,42,18-24,M,BLACK
4,09/28/2021,NaN,NaN,B,44,25-44,M,BLACK
...,...,...,...,...,...,...,...,...
155502,01/10/2021,"ROBBERY,OPEN AREA UNCLASSIFIED",ROBBERY,B,46,45-64,M,BLACK
155503,02/03/2021,WEAPONS POSSESSION 1 & 2,DANGEROUS WEAPONS,K,67,18-24,M,BLACK
155504,02/13/2021,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,S,121,45-64,M,BLACK
155505,01/04/2021,WEAPONS POSSESSION 1 & 2,DANGEROUS WEAPONS,K,73,25-44,M,BLACK
155506,02/06/2021,CRIMINAL MIS 2 & 3,CRIMINAL MISCHIEF & RELATED OF,Q,102,18-24,M,ASIAN / PACIFIC ISLANDER

In [8]:
df_tidy.shape

(155507, 8)

In [12]:
date_fil = df_tidy["arrest_date"] == "['01/01/2021':'12/31/2021']"
date_fil

0         False
1         False
2         False
3         False
4         False
          ...
155502    False
155503    False
155504    False
155505    False
155506    False
Name: arrest_date, Length: 155507, dtype: bool

In [13]:
date_fil.value_counts()

False    155507
Name: arrest_date, dtype: int64